### ISSUE TITLE
egl初始化失败

### ISSUE THREAD

**Issue by zhuchen1109** [Faceunity/FuAgoraDemoDroid#1]
求教，使用这个demo，在三星S7上有时候会出现egl初始化失败
具体log：
02-04 18:55:11.213 17340-24909/io.agora.openvcall E/faceunity-wrapper: EGL context already set up
02-04 18:55:11.223 17340-24909/io.agora.openvcall D/libEGL: eglInitialize EGLDisplay = 0xde2da8b4
02-04 18:55:11.223 17340-24909/io.agora.openvcall D/faceunity-wrapper: EGLContext created, client version 3
02-04 18:55:11.223 17340-24909/io.agora.openvcall E/libEGL: eglMakeCurrent:1030 error 3002 (EGL_BAD_ACCESS)
02-04 18:55:11.223 17340-24909/io.agora.openvcall E/faceunity-wrapper: eglMakeCurrent failed
02-04 18:55:11.263 17340-24904/io.agora.openvcall W/AudioManager: setStreamMute is deprecated. adjustStreamVolume should be used instead.
02-04 18:55:11.733 17340-17390/io.agora.openvcall D/AudioDevice Java: Java minimum playback buffer size is 7088
02-04 18:55:11.733 17340-17390/io.agora.openvcall D/AudioDevice Java: Java playback buffer size is 7088
02-04 18:55:11.763 17340-17390/io.agora.openvcall D/AudioDevice Java: Java play sample rate is set to 44100
02-04 18:55:11.773 17340-17390/io.agora.openvcall D/AudioDevice Java: Java minimum recording buffer size is 1280
02-04 18:55:11.783 17340-17390/io.agora.openvcall D/AudioDevice Java: Java recording sample rate set to 16000
02-04 18:55:11.803 17340-17390/io.agora.openvcall D/AudioDevice Java: AcousticEchoCanceler.isAvailable: true
02-04 18:55:11.823 17340-17390/io.agora.openvcall D/AudioDevice Java: AcousticEchoCanceler name: Acoustic Echo Canceler, implementor: Qualcomm Fluence, uuid: 0f8d0d2a-59e5-45fe-b6e4-248c8a799109
02-04 18:55:11.823 17340-17390/io.agora.openvcall D/AudioDevice Java: AcousticEchoCanceler.getEnabled: true
02-04 18:55:11.863 17340-17389/io.agora.openvcall W/AudioManager: setStreamMute is deprecated. adjustStreamVolume should be used instead.
02-04 18:55:11.863 17340-17389/io.agora.openvcall I/System.out: [Thread-30477] DEBUG MyEngineEventHandler$1 onJoinChannelSuccess aa 664963166 664963166 1658
02-04 18:55:11.863 17340-17389/io.agora.openvcall I/System.out: [Thread-30477] DEBUG ChatActivity onJoinChannelSuccess aa 664963166 1658
02-04 18:55:11.883 17340-17340/io.agora.openvcall W/AudioManager: setStreamMute is deprecated. adjustStreamVolume should be used instead.
02-04 18:55:11.883 17340-24909/io.agora.openvcall E/faceunity-wrapper: no egl context
02-04 18:55:11.893 17340-24909/io.agora.openvcall E/faceunity-wrapper: no egl context

**Comment by AndroidInternal** [comment]
时间有些久远了，这个问题还存在吗。。这个问题看上去是gl context已经存在了。至于为什么已经存在，可能是之前没有释放掉。
